deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ parkrwadm@132.148.247.87:/var/www/html
  on:
    branch: master
language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install: npm install
script: npm run build
addons:
  ssh_known_hosts: 132.148.247.87
before_deploy:
- openssl aes-256-cbc -K $encrypted_466c150099c3_key -iv $encrypted_466c150099c3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa