deploy:
- provider: s3
  cache_control: 'no-cache, max-age=0' # no cache and revalidate
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $BUCKET_DEV
  acl: public_read
  local_dir: build
  skip_cleanup: true
  on:
    branch: 'develop'
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ parkrwadm@132.148.247.87:/var/www/html
  on:
    branch: master
language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install: npm install
script: npm run build
addons:
  ssh_known_hosts: 132.148.247.87
before_deploy:
- npm test
- openssl aes-256-cbc -K $encrypted_78ec4095244e_key -iv $encrypted_78ec4095244e_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa